services:
  app:
    image: app
    build:
      context: ./frontend/
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: app
  backend:
    image: backend
    build:
      context: ./backend/
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
    environment:
      - PORT=3001
    container_name: backend
  nginx:  
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    