services:
  app:
    image: app
    build:
      context: ./frontend/
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: app
  backend:
    image: backend
    build:
      context: ./backend/
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 3001:3001
    environment:
      - PORT=3001
    container_name: backend